<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="QRCoder">
      <HintPath>lib\QRCoder.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Monitoring.Blazor.Tests\**\*.cs" />
    <Content Remove="Monitoring.Blazor.Tests\**\*" />
    <None Remove="Monitoring.Blazor.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="monitoring-blazor.AppHost\**\*.cs" />
    <Content Remove="monitoring-blazor.AppHost\**\*" />
    <None Remove="monitoring-blazor.AppHost\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.local.json" Condition="Exists('appsettings.local.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="appsettings.private.json" Condition="Exists('appsettings.private.json')">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
